### ISSUE TITLE
DVC: import datachain shortcut

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#756]
See this repository as an example: https://github.com/shcheklein/example-datachain-dvc

in `dvc.yaml`:
```yaml
...
stages:
  version_data:
    cmd: python src/dc/index.py
    outs:
    - data/dataset.parquet
```

in `src/dc/index.py`:
```python
from datachain import DataChain, C

(
    DataChain
        .from_storage("s3://dvc-public-versioned/get-started-pools/", type="image", anon=True)
        .filter(C("file.path").glob("*.jpg") | C("file.path").glob("*.png"))
        .to_parquet("data/dataset.parquet")
)
```

This seems to be a very common operation and it's better to support this out of the box in dvc.yaml file level. It can look like this without any python code:
```yaml
...
stages:
  version_data:
    - datchain: "s3://dvc-public-versioned/get-started-pools/.*\.(jpg|jpeg|png)$"
         outs: "data/dataset.parquet"
         anon: True
```

PS: it should also be compatible with SaaS version of DC import
